name: Build and Test Programs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    name: Build Programs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential
      
      - name: Build programs
        run: | 
          mkdir -p build
          gcc -o build/flush_build 01.IO_Flush/index.c || exit 1
          gcc -o build/over_commit_build 02.Overcommit/main.c || exit 1
          gcc -o build/image.o -c 03.Fractal/image.c || exit 1 
          gcc -c 03.Fractal/fractal.c -o fractal.o -lm
          gcc build/image.o build/fractal.o -o build/fractal -lm

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: build/
  test:
    name: Test Programs
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download executables
        uses: actions/download-artifact@v4
        with:
          name: executables
          path: executables/
      - name: Run all examples
        run: |
          cd executables
          chmod +x *
          echo "Running flush examples"
          echo "Running Default exampl flush and fputs"
          timeout 10s ./flush_build -d || echo "Failed or took too long"
          echo "Running Adding new line example"
          timeout 10s ./flush_build -n || echo "Failed or took too long"
          echo "Running No flush example"
          timeout 10s ./flush_build -s || echo "Failed or took too long"
          echo "Running Redirect example"
          timeout 10s ./flush_build -r > output_redirect.txt || echo "Failed or took too long"
          echo "Running Overcommit examples"
          echo "Reading Help"
          ./over_commit_build -h
          echo "Running the default example"
          timeout 10s ./over_commit_build || echo "Failed or took too long"
          echo "Running fast pauses example"
          timeout 10s ./over_commit_build -m 500 -a write -p 100000 -d 10 || echo "Failed or took too long"